### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by crondotnet** [johang/btfs#1]
line 285 btfs.cc , std::auto_ptr<libtorrent::alert> a = session->pop_alert();

auto_ptr is deprecated , use unique_ptr instead or shared_ptr

just a suggestion.

**Comment by Alienwaren** [comment]
Is it really a problem?

**Comment by crondotnet** [comment]
if deprecation is not enough ....
"auto_ptr moves from lvalues using copy syntax and is thus fundamentally unsafe."

...and you can't use them in containers.

src: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4168
