### ISSUE TITLE
Connections keep open after fusermount

### ISSUE THREAD

**Issue by HazCod** [johang/btfs#13]
After a `fusermount -u mnt`, I can see the connections stay open.
![Nethogs output](https://i.imgur.com/0MqA44B.png)

**Comment by johang** [comment]
If you have open files when you unmount, unmont will fail and btfs will keep running. Maybe that's what happened.

**Comment by HazCod** [comment]
I unmounted successully AFAIK

**Comment by johang** [comment]
Was btfs still running?

**Comment by HazCod** [comment]
Sec, retrying. Also, trying to cancel a copy in progress doesn't work.

**Comment by johang** [comment]
I suspect the connections you see are half-open or stale TCP connections. I.e. connections that were improperly terminated by btfs on shutdown, and are about to timeout now when the process is dead. If you wait a few minutes they should disappear.

Maybe btfs is missing some call to libtorrent in btfs_destroy to perform a more graceful shutdown.

**Comment by HazCod** [comment]
@johang, so I did this with autofs and all connections seem to go away. Sorry for disturbing
