### ISSUE TITLE
Ability for autofs mount

### ISSUE THREAD

**Issue by HazCod** [johang/btfs#14]
Hello,

I currently cannot get it to work with fstab/autofs. Is there something you need to implement for this?

**Comment by johang** [comment]
Should not need code changes in btfs to achieve this.

**Comment by PlasmaPower** [comment]
Does [this](http://stackoverflow.com/a/8108474/3352674) work for you? (instead of `vdbfs.py`, use `btfs`)

**Comment by HazCod** [comment]
Well I was trying to make it work with [AutoFS](https://help.ubuntu.com/community/Autofs) but failed to make it work, so I thought this just didn't support mounting using fstab. I did try the symlink to make `mount -t btfs` work.

**Comment by HazCod** [comment]
@PlasmaPower , @johang , I can confirm it works with fstab, but not with autofs
