### ISSUE TITLE
get stuck at processing files within the mounted torrent around the size of 2,147 GB

### ISSUE THREAD

**Issue by lucendio** [johang/btfs#15]
OS: 14.03 LTS 64bit

I am using ``btfs`` to mount torrents in order to copy some containing files into my host fs. 

I tested copying with shell (``cp``) or GUI (file explorer). The shell doesnt return, the progress dialog can be closed but unmounting does not work: ``fusermount -u`` results in ``failed to unmount, Device or resource budy``. I have to ``kill`` the process first. HDD space is definitely not the issue here.
I tried different torrents. I coundnt find any ``--verbose`` flag to get you with more info, sorry.

**Comment by PlasmaPower** [comment]
You could pass `-d` to it for debugging info. In addition, what does the log file contain?

**Comment by lucendio** [comment]
``-d`` shows nothing abnormal at the point where suddenly everything stops. the last one is an ``handle_piece_finished_alert: 4112``. where do I find the log file of ``btfs``?

**Comment by PlasmaPower** [comment]
It should be in a folder like `btfs-EE7bUi` or something.

**Comment by johang** [comment]
Sounds like an overflow error somewhere. 2.147 GB is about the max size of a 32 bit signed integer.

**Comment by PlasmaPower** [comment]
Good point - I totally forgot that. I'll start looking for possible causes.

**Comment by PlasmaPower** [comment]
Looks like we'll need should switch to `off_t` for all offsets, that is forced to be a 64 bit unsigned integer on 64 bit systems by FUSE headers.

**Comment by PlasmaPower** [comment]
I'll get started on making a PR.

**Comment by PlasmaPower** [comment]
I'm not quite sure how to do this, I don't have a good understanding of the codebase. If someone else wants to take over, please do.

**Comment by johang** [comment]
Yeah, I'll take over. To me it looks like the offset parameter to the Read constructor is the culpit.

**Comment by PlasmaPower** [comment]
I just didn't know if there was anything else that needed changed, and I don't have a >2.1 GB torrent on hand.

**Comment by lucendio** [comment]
I ll check the next release. and re-open if anything might still broken. thanks for your help!

**Comment by lucendio** [comment]
works like charm. many thx!
