### ISSUE TITLE
Add max-upload-rate in default config

### ISSUE THREAD

**Issue by HazCod** [johang/btfs#19]
Is this possible? I can't seem to add additional cli parameters via autofs.

**Comment by HazCod** [comment]
Edit: it does seem I could specify max-upload-rate in OPTIONS below, correct?

**Comment by johang** [comment]
Sounds like a autofs problem to me. Not a btfs problem.

**Comment by HazCod** [comment]
I will close this.

For the curious ones; I moved `/usr/local/bin/btfs` to `/usr/local/bin/btfs.orig` and made a file in `/usr/local/bin/btfs` with contents:

```
#!/bin/bash

/usr/local/bin/btfs.orig --max-upload-rate=100 $@
```
