### ISSUE TITLE
This only works on Ubuntu?

### ISSUE THREAD

**Issue by williamle8300** [johang/btfs#2]
yo.

**Comment by johang** [comment]
To my knowledge, there's nothing Ubuntu specific in the code. You can probably build and run it on other distros too, as long as the dependencies are satisfied.

**Comment by williamle8300** [comment]
I have a Mac? :+1: :-1: ?

**Comment by williamle8300** [comment]
Sick library by the way. Great work!

**Comment by johang** [comment]
FUSE exists for OS X in the form of MacFUSE, so I guess it can work. I don't own a Mac so I can't tell for sure.

**Comment by williamle8300** [comment]
Oh yea. I'll check it out and see if it works.

**Comment by johang** [comment]
There's a PR that fixes OS X support. Try that!
