### ISSUE TITLE
Does brfs seed as well?

### ISSUE THREAD

**Issue by bsima** [johang/btfs#34]
Or does it just download from the torrent without seeding?

**Comment by bsima** [comment]
Looks like there is a command line switch for it [here](https://github.com/johang/btfs/blob/master/src/btfs.cc#L801) but I don't see where it's actually used in the code

**Comment by johang** [comment]
It seeds (i.e. uploads chunks) as long as it's mounted. It works like a regular Bittorrent client in that sense.

**Comment by bsima** [comment]
thanks!
