### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by oliverpool** [johang/btfs#38]
Do you think that it might be possible to get btfs to work under windows? (using something like [dokan](https://github.com/dokan-dev/dokany/wiki/FUSE) for instance)

If yes, what do you estimate the work to do in order to adapt the current code?

Thanks!

**Comment by johang** [comment]
BTFS relies heavily on FUSE and libtorrent. I know libtorrent works on Windows so if Dokan is compatible with FUSE it should work. I can't estimate the work since I don't know Dokan and Windows very well.

**Comment by RulerOf** [comment]
[WinFSP](http://www.secfs.net/winfsp/download/) would likely be worth a look.  You can see how it supports things like SSHFS in the clip on that page.

Source is [here on GitHub, too](https://github.com/billziss-gh/winfsp).

**Comment by johang** [comment]
Patches are welcome.
