### ISSUE TITLE
fuse: missing mountpoint parameter

### ISSUE THREAD

**Issue by thoradia** [johang/btfs#45]
I have built btfs for LibreELEC.
`btfs magnet mountpoint` returns `fuse: missing mountpoint parameter` and nothing happens.
What I am missing?

**Comment by johang** [comment]
Which version?

**Comment by thoradia** [comment]
Version 2.18

**Comment by johang** [comment]
I think the only way that can happen is if you run a command like this, with no mount point:

`btfs "magnet:?xt=urn:btih:0000000000000000000000000000000000000000"`

**Comment by thoradia** [comment]
Thank you for your feedback.
I forgot the quotes :man_facepalming: 
Closing
