### ISSUE TITLE
compile error in raspbian

### ISSUE THREAD

**Issue by pasztorl** [johang/btfs#49]
I got this message when I try to compile it.

pkg -l| grep torrent
ii  libtorrent-dev:armhf            0.13.7-1                   armhf        C++ BitTorrent library by Rakshasa (development files)
ii  libtorrent-rasterbar-dev        1.1.5-1                    armhf        Development files for libtorrent-rasterbar
ii  libtorrent-rasterbar9           1.1.5-1                    armhf        C++ bittorrent library by Rasterbar Software
ii  libtorrent20:armhf              0.13.7-1                   armhf        C++ BitTorrent library by Rakshasa

make[1]: Entering directory '/usr/local/src/btfs/src'
g++ -std=c++11 -Wall -Wextra -Wconversion -Wsign-compare -Wsign-conversion -Wno-unused-parameter -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse  -DTORRENT_USE_OPENSSL -DBOOST_ASIO_HASH_MAP_BUCKETS=1021 -DBOOST_EXCEPTION_DISABLE -DBOOST_ASIO_ENABLE_CANCELIO -DTORRENT_LINKING_SHARED -I/usr/include/libtorrent   -g -O2   -o btfs btfs-btfs.o -lfuse -pthread  -ltorrent-rasterbar -lboost_system  -lcurl  -lpthread
/usr/bin/ld: btfs-btfs.o: in function `btfs_init(fuse_conn_info*)':
/usr/local/src/btfs/src/btfs.cc:635: undefined reference to `libtorrent::settings_pack::set_str(int, std::string)'
/usr/bin/ld: /usr/local/src/btfs/src/btfs.cc:639: undefined reference to `libtorrent::settings_pack::set_str(int, std::string)'
/usr/bin/ld: btfs-btfs.o: in function `setup()':
/usr/local/src/btfs/src/btfs.cc:213: undefined reference to `libtorrent::file_storage::file_path(int, std::string const&) const'
/usr/bin/ld: /usr/local/src/btfs/src/btfs.cc:240: undefined reference to `libtorrent::file_storage::file_path(int, std::string const&) const'
/usr/bin/ld: btfs-btfs.o: in function `handle_read_piece_alert':
/usr/local/src/btfs/src/btfs.cc:253: undefined reference to `libtorrent::read_piece_alert::message() const'
/usr/bin/ld: btfs-btfs.o: in function `boost::detail::sp_if_not_array<libtorrent::torrent_info>::type boost::make_shared<libtorrent::torrent_info, char*&, boost::reference_wrapper<boost::system::error_code> const>(char*&, boost::reference_wrapper<boost::system::error_code> const&&)':
/usr/include/boost/smart_ptr/make_shared_object.hpp:254: undefined reference to `libtorrent::torrent_info::torrent_info(std::string const&, boost::system::error_code&, int)'
/usr/bin/ld: btfs-btfs.o: in function `populate_metadata':
/usr/local/src/btfs/src/btfs.cc:868: undefined reference to `libtorrent::parse_magnet_uri(std::string const&, libtorrent::add_torrent_params&, boost::system::error_code&)'
collect2: error: ld returned 1 exit status

**Comment by johang** [comment]
Looks like it's linking to wrong version of libtorrent? I can't reproduce this on my Ubuntu machine with same version of libtorrent you have (1.1.5).

**Comment by pasztorl** [comment]
Yes, generally it looks like to wrong version, but I do not have other libtorrent version installed.
If I remove the libtorrent-rasterbar-dev, the configure says:

checking for LIBTORRENT... no
configure: error: Package requirements (libtorrent-rasterbar >= 1.0.0) were not met:

No package 'libtorrent-rasterbar' found

so I think it used the libtorrent-rasterbar-dev 1.1.5-1 armhf package.

**Comment by johang** [comment]
That sounds like a good idea.
