### ISSUE TITLE
It's probably time to make btplay python3

### ISSUE THREAD

**Issue by highvoltage** [johang/btfs#53]
In Debian we're dropping python2 scripts for the bullseye release (planned only in around 2 years from now). btplay seems like it should run just fine in python3, perhaps it's time to make it the default from btfs upstream? If it's done upstream then we wouldn't have to carry a patch for this in Debian.

thanks for all your work!

**Comment by johang** [comment]
Yes, btplay is supposed to support both python2 and python3. Anyway, I changed the shebang. Let me know if this doesn't solve your issue.

**Comment by highvoltage** [comment]
Thanks, yes I think that should do it.
