### ISSUE TITLE
Files added through CLI not showing in Web UI

### ISSUE THREAD

**Issue by sd0minick** [johang/btfs#55]
When I add a file using the following command:

`btfs add file1.txt`

I cannot see the file when I'm looking at this link http://127.0.0.1:5001/btfs/webui

However, If I load a file or create a folder from the web ui, then I run this command in the terminal

`btfs files ls`

I can properly see the files in the CLI

Is there a way to fix this or am I missing something?

Kindly let me know your thoughts

**Comment by johang** [comment]
Wrong project. You're probably looking for this: https://github.com/TRON-US/btfs-webui
