### ISSUE TITLE
Encryption?

### ISSUE THREAD

**Issue by danwdart** [johang/btfs#57]
Hey, does this support encryption? I noticed that that was missing from the man page and I usually use it when I'm using other clients. Ta.

**Comment by johang** [comment]
I believe peer encryption is supported but not enforced.

**Comment by pataquets** [comment]
@johang isn't there any way to tune or pass flags to libtorrent as you do with FUSE with `-o`?

**Comment by johang** [comment]
Not possible. You have to change to source code. See settings_pack in btfs_init.
