### ISSUE TITLE
Add RAM-only mode

### ISSUE THREAD

**Issue by lhartmann** [johang/btfs#58]
Please add a mode that does not save anything to the backing hard disk.

Reasoning:
- Allows amnesiac usage, untraceable, no clues left on hard disk.
- Allows diskless usage.
- Allows streaming of huge files, larger than local storage.

I tried to use BTFS for clonezilla image transfers, but there is no disk available during that process, so it did not work.

**Comment by johang** [comment]
I believe you can achieve this by using the `--data-directory` parameter and set it to some tmpfs or ramfs.

**Comment by lhartmann** [comment]
Closing in favor of #59, which should solve both.
