### ISSUE TITLE
Link to -latomic everywhere or just on platforms that need it?

### ISSUE THREAD

**Issue by petterreinholdtsen** [johang/btfs#61]
Hi.  I just noticed from https://buildd.debian.org/status/package.php?p=btfs how this program fail to build on a few architectures where -latomic is needed for some atomic operations the compiler do not handle natively.  Please have a look at adjusting the build system to link with -latomic.  It should be safe to do on all platforms.

**Comment by johang** [comment]
Thanks for reporting this. I agree -- it should be safe on all platforms.

**Comment by johang** [comment]
It seems -latomic is not safe on all platforms. MacOS is weird. I'll find a better solution.

**Comment by johang** [comment]
Fixed for both Linux and MacOS in d3872a93cdf0e6462a9032cdeb0a357d571aec0f (v2.21).
