### ISSUE TITLE
RAM consumption

### ISSUE THREAD

**Issue by ryzhovau** [johang/btfs#67]
Is there any way to reduce memory usage? I'm trying to [port](https://github.com/Entware/graveyard/tree/master/btfs) `btfs` for embedded devices and found that 256MB RAM is not enough to running it.

Ready to test any thoughts on mipsel/x86/arm hardware.

**Comment by pataquets** [comment]
I guess this might decrease usage somewhat at your networking stack: #69

**Comment by johang** [comment]
Check out libtorrent::min_memory_usage() in session.hpp in libtorrent.

**Comment by ryzhovau** [comment]
Closing for now.
