### ISSUE TITLE
Mount multiple torrents with a single btfs instance

### ISSUE THREAD

**Issue by pataquets** [johang/btfs#68]
By accepting additional torrents after the first one.
Subdirectories for each torrent can be named after torrent name or BTIH, if missing.

**Comment by johang** [comment]
You can achieve this by just calling btfs multiple times with different parameters and mount points.

**Comment by pataquets** [comment]
I was meaning but running just a single instance of `btfs` (issue title updated to clarify).
Something along doing the same magic on a directory list loop.

**Comment by qithron** [comment]
The use case is probably legit. Not torrent, but kinda the same thing, I used to mount nearly 100 archives using `google/fuse-archive`. Imagine mount or htop. But tbh, I would prefer btfs handle 1 torrent at a time, which is very simple, except if the name is multi-btfs.

**Comment by johang** [comment]
btfs is one torrent per btfs instance and this will probably not change.
